POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "aji@example.com",
  "password": "password123",
  "name": "Wahyu Aji"
}

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "aji@example.com",
  "password": "password123"
}